# version: '3'

# services:

#   backend:
#     image: rkepha/yolo-backend:1.0.1-buster
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongodb
#     environment:
#       - MONGODB_URI=mongodb://mongodb:27017/yolomy
#     command: npm run start


#   client:
#     image: rkepha/yolo-client:1.0.1-buster
#     depends_on:
#       - mongodb
#     environment:
#       - MONGODB_URI=mongodb://mongodb:27017/yolomy
#     ports:
#       - "3000:3000"
#     command: npm start

#   mongodb:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:




version: '3'

services:
  backend:
    image: rkepha/yolo-backend:1.0.1-buster
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy

  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - ./data:/data/db

  client:
    image: rkepha/yolo-client:1.0.1-buster
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://backend:5000
