# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: yolo-client
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: yolo-client
#   template:
#     metadata:
#       labels:
#         app: yolo-client
#     spec:
#       containers:
#         - name: yolo-client
#           image: rkepha/yolo-client:1.0.1-buster
#           ports:
#             - containerPort: 3000
#           env:
#             - name: REACT_APP_API_URL
#               value: "http://yolo-backend-service:80"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: yolo-client-service
# spec:
#   selector:
#     app: yolo-client
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
#   type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: rkepha/yolo-client:1.0.1-buster
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://backend-service:5000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
