# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: yolo-backend
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: yolo-backend
#   template:
#     metadata:
#       labels:
#         app: yolo-backend
#     spec:
#       containers:
#         - name: yolo-backend
#           image: rkepha/yolo-backend:1.0.1-buster
#           ports:
#             - containerPort: 5000
#           env:
#             - name: MONGODB_URI
#               value: "mongodb://mongo:27017/yolomy"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: yolo-backend-service
# spec:
#   selector:
#     app: yolo-backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rkepha/yolo-backend:1.0.1-buster
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017/yolomy
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
