apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-mongo
  template:
    metadata:
      labels:
        app: yolo-mongo
    spec:
      containers:
        - name: yolo-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo-service
spec:
  selector:
    app: yolo-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
