apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: yolo-client
          image: rkepha/yolo-client:1.0.1-buster
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://yolo-backend-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-client-service
spec:
  selector:
    app: yolo-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
